### ISSUE TITLE
installing errors

### ISSUE THREAD

**Issue by justjim1220** [eouia/MMM-GoogleTTS#1]
this is happening, Any Ideas?

![screenshot 52](https://user-images.githubusercontent.com/27590633/53664997-d1a6a680-3c2f-11e9-987a-8248376e2eb5.png)

**Comment by eouia** [comment]
Sorry this is not tested on windows. I have no idea to solve it. I cant guarantee this works on windows

**Comment by justjim1220** [comment]
ok, thanks!

**Comment by eouia** [comment]
I'll close this issue too out-of-date. Have a nice day.

**Comment by DMFra** [comment]
Hi i have the same problem on raspberry pi 3, any suggestions?
