### ISSUE TITLE
Different message according to the time of the day

### ISSUE THREAD

**Issue by JohnB7777** [eouia/MMM-GoogleTTS#2]
Hello,

This module is also interesting but I wonder if it's compatible with PIR-Sensor (for example : the morning, le mirror says "good morning" and at a different moment of the day, it says something else).

Thanks !

**Comment by eouia** [comment]
Which PIR Sensor module? Anyway, this module's job is "Speech", so Considering How and what to speak is business of other module. Any module which can be adjusted to emit `TTS_SAY` could order this module to speak. 
```js
this.sendNotification("TTS_SAY", "May the Force be with you")
```

**Comment by JohnB7777** [comment]
This PIR-Sensor : https://www.amazon.com/2013newestseller-HC-SR501-Pyroelectric-Infrared-Detector/dp/B00FDPO9B8

Ok, I guess we can adapt it

**Comment by eouia** [comment]
Yes. that is the sensor itself. but S/W module to use that sensor should be able to send specific notification by configuration adjustment or source-code modification.

**Comment by eouia** [comment]
I'll close this issue because no more feedback. I wish a good luck.
