### ISSUE TITLE
playing sound error

### ISSUE THREAD

**Issue by ddoong** [eouia/MMM-GoogleTTS#3]
![image](https://user-images.githubusercontent.com/36120857/59875811-ac0afc00-93dc-11e9-876b-b862bbf4566c.png)

Hotword로 TTS_SAY를 해서 음성이 나오는지 테스트 하려했는데 위에 사진처럼 에러가나옵니다. 
notificationExec:{
    notification: "TTS_SAY",
    payload: "Hi!" // 이부분은 한국어로도 해봤는데 안되서 영어로도 해봤으나 마찬가지입니다
},

config에서는 voiceName, languageCode, ssmlGender를 한국어로 바꾼거 외에는 default값 사용중입니다.

**Comment by eouia** [comment]
일단 HOTWORD는 제쳐두시고...
GoolgleTTS config에서 `welcome` 필드로 테스트 해보셨나요?

**Comment by ddoong** [comment]
default에 있는것 그대로 적용해도 같은에러로 나옵니다

**Comment by eouia** [comment]
흠.. 저는 잘 되는데.. T_T;; 재현이 안되는 에러가 제일 골치아파요...
일단  HOTWORD는 disabled시켜두시고, (가능하면 다른 모듈도 disabled시키시고)
```js
{
  module: "MMM-GoogleTTS",
  config: {}
},
```
이것만 썼는데도 welcome 메시지가 안나오고 위의 에러가 나온단 말씀이죠?
그런데 위의 에러대로라면, node_helper.js의 113 line에서 이미 에러가 발생했어야 한단 말이죠...
112 line 에 `process.exit()`를 추가해서 저 시점에 MM을 종료하게 한 후, MMM-GoogleTTS 디렉토리에 "temp_output"이라는 파일이 생기는지 확인해보시겠어요?

**Comment by ddoong** [comment]
모듈 다 지우고 저것만 써도 똑같은 에러나오네요 ㅠㅠ
process.exit() 이거 추가하니까 temp_output 생깁니다.

파일생성되고 process.exit() 추가했던거 지우고 다시해봤는데도 에러나고 파일도 없어지네요

**Comment by eouia** [comment]
저도 다시 RPI 포맷하고 다시 설치하고 테스트해보았지만, 특별한 문제 없이 잘 되는데요..  T_T
`process.exit()` 한 상태에서 만들어진 temp_output에 대해서, `aplay temp_output` 이거 실행해보시겠어요? 실제로 모듈이 하는 일도 저거구요.
