### ISSUE TITLE
Error after Initialized

### ISSUE THREAD

**Issue by chanapai** [eouia/MMM-GoogleTTS#4]
Hi I got Error after Initialized

I use Raspberry Pi4 

[16:10:56.753] [LOG]    Launching application.
[16:10:59.231] [LOG]    [GGLTTS] Initialized.
[16:10:59.326] [LOG]    [GGLTTS] Today's quota used: 0
/home/pi/MagicMirror/node_modules/electron/dist/electron js/electron.js: symbol lookup error: /home/pi/MagicMirror/modules/MMM-GoogleTTS/node_modules/grpc/src/node/extension_binary/electron-v3.1-linux-arm-glibc/grpc_node.node: undefined symbol: __atomic_store_8
npm ERR! code ELIFECYCLE
npm ERR! syscall spawn
npm ERR! file sh
npm ERR! errno ENOENT
npm ERR! magicmirror@2.10.1 start: `./run-start.sh`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the magicmirror@2.10.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:

**Comment by eouia** [comment]
You might be failed on `./node_modules/.bin/electron-rebuild` step during installation.

**Comment by chanapai** [comment]
Thank you for reply 

I have follow the Installation instruction and it completely find.

what can I do for the failed of ./node_modules/.bin/electron-rebuild 

I also use MMM-AssistantMk2 and MMM-Hotword. and also work find.

**Comment by eouia** [comment]
Just do again electron-rebuild. If success, `Rebuild complete` message will be shown.
If failed, detailed information is needed what happened on that step.

**Comment by chanapai** [comment]
I have try rebuild the electron 
it show

npm WARN grunt-stylelint@0.13.0 requires a peer of stylelint@^12.0.0 but none is installed. You must install peer dependencies yourself.

+ electron-rebuild@1.10.0
updated 1 package and audited 3139 packages in 25.197s

18 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

But still got the same error. when I run the program

**Comment by chanapai** [comment]
update 

I have try reboot the raspberry pi, when the system turn on and Magic Mirror always automatic run and the TTS start speaking!, it say the default welcome: ["May the force be with you", "Live long and prosper"].

Unfortunately, when I restart by using pm2 restart MagicMirror or npm start in the MagicMirror directory, It still error the same.

**Comment by eouia** [comment]
> It still error the same.

It is definitely weird. Is it really same error? Because, `and the TTS start speaking!` means, your electron-rebuild was a success. 
 `symbol lookup error: /home/pi/MagicMirror/modules/MMM-GoogleTTS/node_modules/grpc/src/node/extension_binary/electron-v3.1-linux-arm-glibc/grpc_node.node: undefined symbol: __atomic_store_8` should not happen again. 

Hmmm.... try this;
```
sudo apt-get install gcc-7
gcc -v
# your gcc version will be shown, it has to be 7.x


cd ~/MagicMirror/modules/MMM-GoogleTTS
npm install grpc@1.23.4
npm install --save-dev electron-rebuild
./node_modules/.bin/electron-rebuild
```

**Comment by chanapai** [comment]
Update !!

It finally done!! 

This is work very well.

> sudo apt-get install gcc-7
>gcc -v
># your gcc version will be shown, it has to be 7.x

>cd ~/MagicMirror/modules/MMM-GoogleTTS
>npm install grpc@1.23.4
>npm install --save-dev electron-rebuild
>./node_modules/.bin/electron-rebuild


Thank you so much!
I really appreciate it.
