### ISSUE TITLE
Modules.

### ISSUE THREAD

**Issue by Alan-Lan2** [eouia/MMM-GoogleTTS#5]
Hello, my question is about whether it is necessary to install another module such as the MMM-Hotword ?.  And how can I make MMM-GoogleTTS interact with other modules?

**Comment by eouia** [comment]
Hmmm....
If your module can emit some custom/predefined notification, you can make this module to say something. 
For example;
`clock` module will broadcast `CLOCK_MINUTE` notification on every minute. You can make this module say "It's OO o'clock" at that hour. (Frankly speaking, it needs additional MMM-NotificationTrigger to translate `clock`'s notification into understandable message, anyway. )

For usage, read README plz.

**Comment by Alan-Lan2** [comment]
Thank you very much., I have another question, I have investigated on the subject so that the mirror listens to me, but I do not succeed.  I have edited a file called .asoundrc and it doesn't work for me.  I would be grateful if you could help me with that problem.

**Comment by eouia** [comment]
What it means ` have investigated on the subject so that the mirror listens to me,`?
Does it mean `You want to order something with your voice like Siri or Google Assistant`?

**Comment by Alan-Lan2** [comment]
Yes, I mean the microphone setting for the mirror to hear me.

**Comment by eouia** [comment]
That is not related to this module. TTS means Text-To-Speach, not Speach-To-Text (STT).

**Comment by Alan-Lan2** [comment]
Thank you very much for your attention, friend.
